### ISSUE TITLE
Chrono vulnerability and fix

### ISSUE THREAD

**Issue by Rusty-Weasel** [DamianRyse/count_test#1]
**Before:**
![image](https://github.com/DamianRyse/count_test/assets/61587283/b782915b-5e32-4b5c-9aa7-fc0b1c401c2a)

**How to fix it:**
``` 
[dependencies]
chrono = { version = "0.4.38", features = ["std"] }
```

**Result after fix:**
![image](https://github.com/DamianRyse/count_test/assets/61587283/301161c4-1ea3-4349-b758-be93d86409ef)

**Comment by DamianRyse** [comment]
SecVuln fixed. Thanks!
